-- CREATE TABLE organisations
-- (
-- 	id SERIAL PRIMARY KEY,
-- 	name VARCHAR(128) NOT NULL,
-- 	city VARCHAR(128) NOT NULL,
-- 	address VARCHAR(128),
-- 	topic VARCHAR(32) NOT NULL,
-- 	url VARCHAR NOT NULL,
-- 	donate_url VARCHAR NOT NULL,
-- 	discription VARCHAR NOT NULL
-- );
-- DROP TABLE organisations;

---- ('Hadassah-Israel', %s, 'https://hadassah-israel.org/', 'Are you looking for a connection with other English speaking women who have made Aliyah?Want to make new friends, be part of a dynamic social group with regular meetings, support and volunteer at the Hadassah hospitals?Are you a life member of Hadassah in America? Life membership of Hadassah is transferrable to Hadassah-Israel, and you will continue to receive the quality Hadassah Magazine.Hadassah-Israel is a volunteer, Zionist, non-partisan women’s organization with chapters and groups all over the country. The organization works toward improving the quality of life in Israel in regards to health, education, new-immigrant absorption, women’s status and children at risk. Annual conferences, health study days, and national meetings provide stimulating topics and social interaction with members throughout the country.Join us -we will direct you to a chapter near your home.'),
---- ('Magen David Adom', %s, 'https://www.mdais.org/en/volunteers', 'Magen David Adom (MDA), Israel's national emergency medical service and blood bank, offers a dynamic Volunteer Program that engages individuals in various aspects of lifesaving and community support. As a Magen David Adom volunteer, participants receive comprehensive training in emergency medical response, first aid, and disaster relief, enabling them to serve as vital assets during crises and everyday emergencies. Volunteers contribute their time and skills across a range of activities, including ambulance assistance, blood drives, community education, and humanitarian aid efforts. Through their dedication and commitment, Magen David Adom volunteers play a crucial role in safeguarding public health and safety, making a meaningful difference in communities across Israel.')
---- ('Latet', %s, 'https://www.latet.org.il/en/volunteering/', 'Latet, one of Israel's largest charitable organizations, offers impactful Volunteer Programs that address poverty and promote social justice throughout the country. Through Latet's Volunteer Programs, individuals have the opportunity to engage in a variety of initiatives aimed at assisting disadvantaged populations. Volunteers play a crucial role in distributing food aid, organizing events, conducting outreach activities, and providing support to vulnerable individuals and families. Latet empowers volunteers to make a tangible difference in their communities by fostering connections, promoting empathy, and creating positive change. Through their dedication and collective efforts, Latet volunteers contribute to building a more equitable and compassionate society in Israel.')
---- ('Yad Sarah', %s, 'https://yadsarah.org/about-us/', 'Yad Sarah, a prominent Israeli organization dedicated to assisting individuals with disabilities and the elderly, offers enriching Volunteer Programs that embody compassion and community support. Through Yad Sarah's Volunteer Programs, individuals have the opportunity to engage in a range of impactful activities, including assisting with medical equipment rentals, providing transportation services, offering companionship to those in need, and participating in educational and recreational programs. Volunteers play a vital role in enhancing the quality of life for those served by Yad Sarah, fostering connections, and promoting independence and well-being. With their dedication and kindness, Yad Sarah volunteers contribute to creating a more inclusive and supportive society in Israel.')
---- ('WWOOF', %s, 'http://www.wwoof.org.il/guide/en', 'WWOOF (World Wide Opportunities on Organic Farms) offers transformative Volunteer Programs that connect individuals with sustainable agriculture and organic farming practices worldwide. Through WWOOF Volunteer Programs, participants have the unique opportunity to live and work on organic farms, gaining hands-on experience in various aspects of farming, permaculture, and sustainable living. Volunteers engage in tasks such as planting, harvesting, animal care, and eco-building, while immersing themselves in the local culture and community. WWOOF empowers volunteers to learn new skills, foster connections with nature, and contribute to environmental stewardship and food sovereignty efforts globally. With WWOOF, volunteers embark on meaningful journeys of discovery, growth, and purposeful engagement in sustainable agriculture.')

-- INSERT INTO organisations (name,city,address,topic,url,donate_url,discription)
-- VALUES
-- ('Sar-el', 'Kiryat Shmona', '953 Kiron 5510802, Israel','Military', 'https://www.sar-el.org/','https://www.jgive.com/new/en/usd/collect/donation-targets/87538/amount', 'All of our program options offer prospective volunteers an opportunity to live and work besides Israeli soldiers and gain an insider view of Israel. You will work alongside soldiers, base employees, and other volunteers on an Israel Defense Forces (IDF) base, performing non-combat civilian support duties such as packing medical supplies, repairing machinery and equipment; packing and checking all kinds of equipment as well as cleaning, painting, and maintaining the base. SAR-EL offers the IDF logistical support throughout Israel through the efforts of our volunteers.'),
-- ('Livnot U''Lehibonot', 'Safed', 'Simtat Alkabetz 17, Safed, Israel','Social', 'https://www.livnot.org/','https://www.livnot.org/donate', 'Livnot U’Lehibanot is an Israel Experience Program for young Jewish people who have little background or affiliation with Judaism or their Jewish communities. As part of the programs, Livnot participants volunteer in a variety of community service projects in Tzfat and other areas of Northern Israel. Individual volunteers are welcome to join the Livnot volunteers in renovating and restoring local parks, excavating archeological ruins of Tzfat, renovating apartments of elderly and disabled residents and working in soup kitchens, libraries, old age homes and other venues in Tzfat. In Jerusalem, Livnot volunteers can join the Livnot work crews that repair and paint apartments of disadvantaged residents of Beit Shemesh and Jerusalem. There are one-week ($195) and two-week ($300) programs available. Click here to apply for either program.'),
-- ('Ascent', 'Tzfat', '24 Jerusalem Street','Social', 'https://www.myascent.org/events-2/volunteering/','https://www.myascent.org/donate/', 'From Ascent’s center in the Old City of Tzfat, in the north of Israel, summer volunteers engage in community development while participating in Ascent’s classes and activities for a discounted rate. Volunteer activities include working on a local organic farm, doing art activities with the elderly and working in a soup kitchen. Ascent’s historic building with stunning views of the hills of the Galilee offers comfortable hostel accommodations and serves as a meeting place and launching pad for personal spiritual exploration for travelers and students from around the world. Participants in the volunteer program can enjoy Shabbat hospitality, daily classes in mysticism, guided tours, hikes and live music alongside the participants in Ascent’s other programs. Ascent activities are geared towards young Jewish men and women looking to grow in their understanding of Judaism.'),
-- ('Yad Ezra', 'Jerusalem', 'Shim’on Rokah Street 28, Jerusalem, Israel','Social', 'https://www.yadezra.net/','https://www.yadezra.net/donation_e.php', 'Yad Ezra Veshulamit is an organization that distributes food for the needy and helps thousands of hungry families. Come help package food in boxes/bags.Please book before coming to volunteer. This volunteer opportunity is suitable for both Hebrew and English speakers. Big groups are welcome!'),
-- ('Israel Guide Dog Center for the Blind', 'Rishon LeZiyyon', 'Beit Oved near Rishon Letzion','Health', 'https://www.israelguidedog.org/','https://www.israelguidedog.org/donate-now/', 'The Israel Guide Dog Center for the Blind aims to improve the quality of life for visually impaired individuals by providing them with professionally trained guide dogs. Volunteers play a crucial role in supporting the center''s mission and operations.'),
-- ('African Community Center', 'Jerusalem', 'Jerusalem African Community Center','Social', 'https://www.jacc.org.il/volunteer-eng','https://www.jacc.org.il/donate-eng', 'Come Volunteer with the Jerusalem African Community Center, a community based organization led jointly by Israeli and African activists in Jerusalem.  The JACC promotes quality of life and overall well-being for African migrants, refugees and asylum seekers in Jerusalem.  We also seek to foster community leadership and facilitate dialogue and neighborly relations between residents of the city.  This takes place through provision of personalized assistance and support, education and rights awareness, programs for children and families and humanitarian aid. There is a wide variety of options in which you can volunteer, such as- teaching English/ Hebrew, tutoring children, any sort of professional (teacher, translator, social worker, psychologist).'),
-- ('Pantry Packers', 'Jerusalem', 'Derech Moshe Baram Talpiot, Jerusalem','Social','https://pantrypackers.org/schedule-a-visit/','https://pantrypackers.org/schedule-a-visit/?form=FUNBNXPXQBY', 'Every month Pantry Packers delivers crates containing all the necessary foods and household maintenance supplies to Israel’s poorest families and senior citizens. Pantry Packers maintains a packing plant in Jerusalem where visitors and tourists may partner in its efforts by helping pack food staples which are then included in the Pantry Packers crates.'),
-- ('Jerusalem Society for the Prevention of Cruelty to Animals (JSPCA)', 'Jerusalem', '14 Derech Beit Lechem','Animals', 'https://jspca.org.il/','https://jspca.org.il/donation/', 'Individuals interested in supporting the JSPCA Pet Project can do so in various ways:Adopting a pet from the shelter,Donating funds or supplies to support the care of animals,Volunteering time to assist with animal care, outreach, or administrative tasks,Spreading awareness about the organization''s mission and encouraging responsible pet ownershipBy supporting the JSPCA Pet Project, individuals can make a positive difference in the lives of animals in Israel and contribute to the broader goal of promoting compassion and respect for all living creatures.');

SELECT * FROM organisations;

-- CREATE TABLE israel_citys
-- (
-- id SERIAL PRIMARY KEY,
-- name VARCHAR(50),
-- latitude FLOAT,
-- longitude FLOAT,
-- cityId INT
-- );

-- SELECT * FROM israel_citys;